name: PR CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  format-and-lint-check:
    name: Node format and lint check
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Prettier check
        run: npm run prettier-check

      - name: ESLint check
        run: npm run lint-check

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install lizard
        run: pip install --disable-pip-version-check --no-input lizard

      - name: Run lizard on main Lambda file only
        run: |
          # Check only the main file and fail on warnings
          # -C: cyclomatic complexity threshold (warn if function > 10)
          # -L: maximum function length (lines) threshold (warn if function > 120)
          lizard -l javascript -C 10 -L 120 src/index.mjs